name: radiofind

services:

  db:
    image: postgres:17

    environment:
      POSTGRES_DB: radiofind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d radiofind"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../rf-back
      dockerfile: Dockerfile

    image: radiofind-back:dev

    env_file:
      - .env

    environment:
      DB_URL: jdbc:postgresql://db:5432/radiofind
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      AVATARS_PATH: /app/storage/avatars

    volumes:
      - avatar-data:/app/storage/avatars

    expose:
      - "8080"

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped

  frontend:
    build:
      context: ../rf-front
      dockerfile: Dockerfile

    image: radiofind-front:dev

    environment:
      NG_ALLOWED_HOSTS: localhost
      NG_TRUST_PROXY_HEADERS: "x-forwarded-host,x-forwarded-proto,x-forwarded-for,x-forwarded-port"

    expose:
      - "4000"

    depends_on:
      - backend

    restart: unless-stopped

  nginx:
    image: nginx:alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - frontend
      - backend

    restart: unless-stopped

volumes:
  db-data:
  avatar-data:
